config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :services do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, except: [:new, :create]

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :service

  # Validaciones
	validates :check_in, :check_out, :price, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  # Foto
  has_many_attached :photos

  #Asociaciones
  has_many :bookings
  has_many :services, through: :bookings

  # Validaciones
	validates :breed, :name, length: { minimum: 2 }
  validates :breed, :name, :description, :date_of_birth, :weight, :size, :photos, presence:true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  #Asociaciones
  has_many :bookings

  # Validaciones
	validates :price, :activity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #Asociaciones
  has_many :services
  has_many :pets
  has_many :bookings, through: :services
  has_many :bookings, through: :pets
  has_one_attached :photo

  # Geocoder
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # PG Search
  include PgSearch::Model

  pg_search_scope :global_search,
  against: [ :address],
  associated_against: {
    services: [ :walking, :styling, :feeding, :medication ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
	before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :telephone, :role, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address, :telephone, :role, :photo])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.pets.map(&:bookings).flatten
  end

  def new
    @booking = Booking.new
    @pets = current_user.pets
    @service = Service.find(params[:service_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.service = Service.find(params[:service_id])
    @booking.price = @booking.service.price * (@booking.check_out - @booking.check_in).to_i

    @booking.save!
    redirect_to bookings_path
  end

  def show
    @booking = Booking.find(params[:id])
    @pet = @booking.pet
    @service = @booking.service
  end

  def edit
    @booking = Booking.find(params[:id])
    @pet = @booking.pet
    @service = @booking.service
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    @booking.price = @booking.service.price * (@booking.check_out - @booking.check_in).to_i
    @booking.save
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private 

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :pet_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    @pet.save!
    redirect_to pets_path
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy!
    redirect_to pets_path
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render :edit
    end
  end

  private 

  def pet_params
    params.require(:pet).permit(:name, :date_of_birth, :breed, :weight, :size, :description, :user_id, photos: [])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    @service.save!
    redirect_to services_path
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy!
    redirect_to services_path
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to @service
    else
      render :edit
    end
  end

  private

  def service_params
    params.require(:service).permit(:activity, :price, :description, :user_id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>

<div>
  <%= booking.check_in %>
  <%= booking.check_out %>
  <%= booking.price %>
  <%# hacer al pet y al servicio una cajita con sus respectivos parametros  %>
  <%= booking.pet.name %>
  <%= booking.service.activity %>
  
  <%# <%= link_to "Edit", edit_service_booking_path(booking.id), class: 'btn btn-info' %>
  <%# <%= link_to "Delete", booking_path(booking.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger' %> %>
</div>
<% end %>

app/views/bookings/new.html.erb
<%= simple_form_for([@service, @booking]) do |f| %>
  <%= f.input :check_in, as: :date %>
  <%= f.input :check_out, as: :date %>

  <%= f.input :pet_id, collection: @pets %>


  <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  
  <%# <%= f.input :weight, input_html: { class: "weight-input", placeholder: "kg" } %>
  
  <%# <%= f.input :size, input_html: { class: "size-input", placeholder: "cm" } %>
  
  <%# <%= f.input :description, input_html: { class: "description-input", placeholder: "Tell us all about your pet! What do they like to play? Do they have any eating preferences? Any medical conditions?" }  %> 
  
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FosterPets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>

  </div>
  <div class="footer-copyright">
    Síguenos en nuestras redes sociales <i class="fas fa-heart"></i> 
  </div>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path 'fosterpet.png'%>">
  <div class="container text-center">
    <h1><strong> Bienvenido al segundo hogar de tus mascotas!</strong></h1>
    <p>En FosterPets nos importa el bienestar y la comodidad de tus mascotas</p>
  </div>
</div>

<div class="card-info d-flex justify-content-center m5">
  <h4 id="funciona">¿Cómo funciona?</h4>
</div>
<div class="row">
  <div class="col-6">
    <div class="card-info-user" >
      <h5>
        <ul>
          <li>Registra a tu mascota</li>
          <p>Cuétanos lo que tengamos que saber de tu mascota.</p>
          <li>Elige a un cuidador</li>
          <p>Revisa a los cuidadores disponibles y elige el que te de más confianza.</p>
          <li>Selecciona los servicios</li>
          <p>¿Quieres que solamente cuidemos a tu mascota? O te gustaria que le demos un baño o algun medicamento.</p>
          <li>Reserva</li>
          <p>Ya que te has decidido por un cuidador y servicios, es hora de reservar el o los días que nos necesitas. .</p>
        </ul>
      </h5>
    </div>
  </div>
  <div class="perritos col-6">
    <%= image_tag("cuidador_de_perros.jpg") %>
  </div>
</div>





<%# <% <hr> %>
<%# <% <% @services.each do |service|
  <%# <div class="col-4"> %>
   <%# <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
    <%= service.name %>
   <%# </div> %>
  <%# </div>
   <% end %>

        <%# <div class="d-flex justify-content-center"> %>
          <%# <%= link_to 'Quiero trabajar', '#', class: 'btn btn-sm btn-flat float-end m-3 me-5' %>
          <%# <%= link_to 'Quiero un servicio', '#', class: 'btn btn-sm btn-flat float-end m-3' %>

app/views/pets/edit.html.erb
<div style="display: flex; justify-content: center; align-items: center;">
  <div class="container main-box p-4 m-4 ">
    <%= simple_form_for(@pet) do |f| %>
    <div class="row">
      <div class="col-md">
        <%= f.input :name %>
      </div>
      <div class="col-md">
        <%= f.input :breed, collection: ["Perro", "Gato", "Tortuga", "Conejo", "Pingüino", "Otro"], prompt: "Select Breed", input_html: { class: "breed-input" } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md">
        <%= f.input :date_of_birth,
                    as: :date,
                    start_year: Date.today.year - 40,
                    end_year: Date.today.year, discard_day: true,
                    required: true,
                    label: "Date of Birth",
                    input_html: { class: "bday-input" },
                    wrapper_html: { class: "bday-input-container" } %> 
      </div>
      <div class="col-md">
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md">
        <%= f.input :weight, input_html: { class: "weight-input", placeholder: "kg" } %>
      </div>
      <div class="col-md">
        <%= f.input :size, input_html: { class: "size-input", placeholder: "cm" } %>
      </div>
    </div>
      
    <%= f.input :description, input_html: { class: "description-input", placeholder: "Tell us all about your pet! What do they like to play? Do they have any eating preferences? Any medical conditions?" }  %>
    
    <div class="text-center">
      <%= f.button :submit, class: 'btn btn-flat mt-3' %>
    </div>
    <% end %>

    <%= link_to 'Atras', pets_path, class: 'btn btn-info mt-3'%>

  </div>
</div>

app/views/pets/index.html.erb
<%# <div style="background-color: #FAE7BF"> %>
  <div class="container text-center mt-4">
    <div class="p-3">
      <h1>Mis mascotas</h1>
      <hr class="solid">
    </div>

    <div class="container">
      <div class="row">
        <% @pets.each do |pet| %>
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card" style="border-radius: 20px">
              <%= link_to pet_path(pet), class: "text-body text-decoration-none" do %>
                <div class="embed-responsive text-center" style="width: 100%; height: 100%; overflow: hidden; margin: auto">
                  <%= image_tag(pet.photos[0], class: "embed-responsive-item img-fluid p-2", style: "border-radius: 20px; object-fit:cover; aspect-ratio: 1/1") if pet.photos.present?%>
                </div>
                <div class="card-body">
                  <h5 class="card-title"><%= pet.name %></h5>
                  <p class="card-text"><%= truncate(pet.description, length: 50) %></p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    
    <div class="row">
      <div class="col-md-12">
        <div class="mb-4">
          <%= link_to new_pet_path, class: "btn btn-flat" do %>
            Registrar mascota
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%# </div> %>

app/views/pets/new.html.erb
<div style="display: flex; justify-content: center; align-items: center;">
  <div class="container main-box p-4 m-4 ">
    <%= simple_form_for(@pet) do |f| %>
    <div class="row">
      <div class="col-md">
        <%= f.input :name %>
      </div>
      <div class="col-md">
        <%= f.input :breed, collection: ["Perro", "Gato", "Tortuga", "Conejo", "Pingüino", "Otro"], prompt: "Select Breed", input_html: { class: "breed-input" } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md">
        <%= f.input :date_of_birth,
                    as: :date,
                    start_year: Date.today.year - 40,
                    end_year: Date.today.year, discard_day: true,
                    required: true,
                    label: "Date of Birth",
                    input_html: { class: "bday-input" },
                    wrapper_html: { class: "bday-input-container" } %> 
      </div>
      <div class="col-md">
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md">
        <%= f.input :weight, input_html: { class: "weight-input", placeholder: "kg" } %>
      </div>
      <div class="col-md">
        <%= f.input :size, input_html: { class: "size-input", placeholder: "cm" } %>
      </div>
    </div>
      
    <%= f.input :description, input_html: { class: "description-input", placeholder: "Tell us all about your pet! What do they like to play? Do they have any eating preferences? Any medical conditions?" }  %>
    
    <div class="text-center">
      <%= f.button :submit, class: 'btn btn-flat mt-3' %>
    </div>
    <% end %>

    <%= link_to 'Atras', pets_path, class: 'btn btn-info mt-3'%>

  </div>
</div>

app/views/pets/show.html.erb
<div class="container main-box mt-4" style="height:300px">
    <div class="row">
      <div class="col-md-6">
        <div class="text-center" style="overflow: hidden; margin: auto">
          <%= image_tag(@pet.photos[0], class: "p-2", style: "width: 100%; height:100%; border-radius: 20px; object-fit:cover; aspect-ratio: 1/1")%>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card-body">
          <h2 class="card-title"><%= @pet.name %></h2>
          <p class="card-text">
            <strong>Breed:</strong> <%= @pet.breed %><br>
            <strong>Description:</strong> <%= @pet.description %><br>
            <strong>Date of Birth:</strong> <%= @pet.date_of_birth %><br>
            <strong>Weight:</strong> <%= @pet.weight %> kg<br>
            <strong>Size:</strong> <%= @pet.size %> cm
          </p>

          <%= link_to edit_pet_path(@pet), class: 'btn btn-primary mr-2' do %>
            Edit
          <% end %>

          <!-- Delete link -->
          <%= link_to pet_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
            Delete
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<div class="container">
  <h2>Edit Activity</h2>

  <%= simple_form_for(@service) do |f| %>
    <%= f.input :activity, :collection => %w["Walking", "Styling", "Medication", "Feeding" "Babysitting"] %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>

  <%= link_to 'Back', services_path, class: 'btn btn-secondary mt-3'%>
</div>

app/views/services/index.html.erb
<div class="container" style="">
  <% @services.each do |service| %>
    <div class="card" style="width=300px; height:100%;">
      <div class="img">
        <% case service.activity %>
        <% when "Walking" %>
          <%= image_tag("walking.png", style: "object-fit: cover; aspect-ratio: 1/1; width: 300px; height:300px")%>
        <% end %>

    <div class="card" style="width=300px; height:100%;">
      <div class="img">
        <% case service.activity %>
        <% when "Styling" %>
          <%= image_tag("styling.png", style: "object-fit: cover; aspect-ratio: 1/1; width: 300px; height:300px")%>
        <% end %>

    <div class="card" style="width=300px; height:100%;">
      <div class="img">
        <% case service.activity %>
        <% when "Medication" %>
          <%= image_tag("medication.png", style: "object-fit: cover; aspect-ratio: 1/1; width: 300px; height:300px")%>
        <% end %>

    <div class="card" style="width=300px; height:100%;">
      <div class="img">
        <% case service.activity %>
        <% when "Feeding" %>
          <%= image_tag("feeding.png", style: "object-fit: cover; aspect-ratio: 1/1; width: 300px; height:300px")%>
        <% end %>

    <div class="card" style="width=300px; height:100%;">
      <div class="img">
        <% case service.activity %>
        <% when "Babysitting" %>
          <%= image_tag("sitting.png", style: "object-fit: cover; aspect-ratio: 1/1; width: 300px; height:300px")%>
        <% end %>

      </div>
      <div class="card-body">
        <h5 class="card-title">
          <%= service.activity %>
        </h5>

        <h5 class="card-title">
          <%= service.price %>
        </h5>
        <p class="card-text">
          <%= truncate(service.description, length: 50) %>
        </p>
      <%= link_to "Editar", edit_service_path(service.id), class: 'btn btn-info' %>
      <%= link_to "Borrar", service_path(service.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger' %>
      <%= link_to 'Reserva', new_service_booking_path(service.id), class: 'btn btn-primary' %>
    </div>
  <% end %>

<%= link_to 'Ofrece un servicio', new_service_path, class: 'btn btn-primary' %>

app/views/services/new.html.erb
<%= link_to "Back", services_path, class: 'btn btn-info' %>

<%= simple_form_for(@service) do |f|%>
  <%= f.input :activity, :collection => ["Walking", "Styling", "Medication", "Feeding", "Babysitting"] %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/services/show.html.erb
<p><%= @service.activity %></p>

<%= link_to 'Back', services_path %>

app/views/shared/_carousel.html.erb
<!-- app/views/shared/_carousel.html.erb -->
<% if images.present? %>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% images.each_with_index do |image, index| %>
        <div class="carousel-item <%= 'active' if index.zero? %>">
          <%= image_tag(image, class: 'd-block w-100', style: 'object-fit:cover; aspect-ratio: 1/1') %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% else %>
  <!-- Default image or placeholder if no images are available -->
  <%= image_tag('default_image.jpg', class: 'd-block w-100') %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Cómo funciona", "/#funciona", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Servicios", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mis mascotas", pets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reservas", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <% if current_user.photo.attached? %>
             <%= image_tag current_user.photo, class: "avatar", alt: "dropdown menu" %>
          <% else %>
             <%= image_tag  "avatar.png", class: "avatar", alt: "dropdown menu" %>
          <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Inicia sesión", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>